### PR TITLE
fix: fixes global login status

### LINKED ISSUE #71: Bug: Reload removes logout button

### PR DESCRIPTION
**Pull request by ChristianMLux**
fixes a bug with the global login status

### CODE REVIEW

File: src/components/UserLogin/UserLogin.vue [hunk 1]
```diff
@@ -50,6 +50,13 @@ export default {
         });
     },
   },
+  /**
+   * computed: {
+    isUserLoggedIn() {
+      return sessionStorage.getItem("userID") === null ? false : true;
+    },
+  },
+   */
```
Comment (robinboehm) [inline src/components/UserLogin/UserLogin.vue]: Please remove commentes code

**Review by robinboehm — CHANGES_REQUESTED** [review]
Fix comment and then merge =)

File: src/components/UserLogin/UserLogin.vue (hunk 1 above)
Comment (ChristianMLux) [reply src/components/UserLogin/UserLogin.vue]: done ;)
